spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employee?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ENC(tqCYcAvj+kQj6FEz0VUC7Q==)
    password: ENC(KtPE5GbmVFHTTMmsR/gSCg==)
    
file:
  text:
    workStartTime: 08-30
    worEndTime: 17-30
      